<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_20</name>
   <tag></tag>
   <elementGuidId>dba1a690-e33b-4667-8420-ae4f755bce4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.price.float-start.d-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div[4]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>abd40a0b-28a9-49cd-bffb-3816f4ac4d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price float-start d-block</value>
      <webElementGuid>95c5076e-f510-4413-8907-8946fec1d088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20฿</value>
      <webElementGuid>0cf60839-5ef1-4484-bed0-1c99570aac26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;content-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-9 col-lg-6  col-md-6 col-xxl-7 col-sm-12&quot;]/div[@class=&quot;product-detail-content&quot;]/div[@class=&quot;new-arrival-content pr&quot;]/div[@class=&quot;d-table mb-2&quot;]/p[@class=&quot;price float-start d-block&quot;]</value>
      <webElementGuid>cb0a87d5-9aed-442f-ba34-78f10f76a9cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[4]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/p</value>
      <webElementGuid>863e9226-029f-4e15-a05d-430923a6652c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(9999 reviews)'])[1]/following::p[1]</value>
      <webElementGuid>096faa87-d64f-453a-86c4-52c43afa69c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soft drink'])[2]/following::p[1]</value>
      <webElementGuid>c7f77a3e-3b60-4db3-a0fb-c627f566db59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In stock'])[1]/preceding::p[1]</value>
      <webElementGuid>3ef36e68-1033-45d2-b92d-49524d09f77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/preceding::p[3]</value>
      <webElementGuid>3b15499c-ab9a-473b-bf6d-aafab3158785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20฿']/parent::*</value>
      <webElementGuid>3a241744-90cb-4330-baff-926d612d5d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>a8d366ee-4386-43cd-9baf-ce8188003a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '20฿' or . = '20฿')]</value>
      <webElementGuid>8b46f58f-a2a3-49d0-b3f0-d9d394ad5789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
