<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_70</name>
   <tag></tag>
   <elementGuidId>dee65c70-ab1b-4873-856d-c027fe4faa44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div[4]/div/div/div/div/div[2]/div/div/div[4]/div[3]/h4[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>4d536533-2da0-43f3-9ffb-2d7a030d59c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 text-primary</value>
      <webElementGuid>3d7fcf5e-a9b8-48f3-b3c1-62af9ed14c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>70฿</value>
      <webElementGuid>e5516c10-4cd9-4a8c-b470-94c7381878dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;content-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-8 col-xxl-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-sm-6 sp15&quot;]/div[@class=&quot;card h-auto b-hover&quot;]/div[@class=&quot;card-body px-3&quot;]/div[@class=&quot;order-menu&quot;]/div[@class=&quot;d-flex align-items-center justify-content-between mb-4&quot;]/h4[@class=&quot;mb-0 text-primary&quot;]</value>
      <webElementGuid>6e03dce0-ba64-408a-83ff-50144c1afdb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[4]/div/div/div/div/div[2]/div/div/div[4]/div[3]/h4[2]</value>
      <webElementGuid>9f521571-e01b-488c-9784-58fd32364bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[2]/following::h4[1]</value>
      <webElementGuid>4b96b7c2-b0b4-4bd8-bee6-5f8841fc2c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pepperoni pizza'])[1]/following::h4[2]</value>
      <webElementGuid>d539e130-69d0-4b16-96c6-b13b892c846c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery'])[1]/preceding::h4[1]</value>
      <webElementGuid>b7aebf87-2c3a-433f-8749-2582c1969ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #3'])[1]/preceding::h4[1]</value>
      <webElementGuid>b8920d59-a76d-4ecf-a391-300df46c2ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='70฿']/parent::*</value>
      <webElementGuid>a640ea78-aeff-4aeb-83d4-052f20bb1a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div[3]/h4[2]</value>
      <webElementGuid>9e158efa-6858-4efd-b672-5acc142b7426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '70฿' or . = '70฿')]</value>
      <webElementGuid>dd38db5b-5472-4391-b49f-4ed4e814f837</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
