<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Soft drink</name>
   <tag></tag>
   <elementGuidId>cb37a2d7-651b-4c9b-9850-2c4fef8d000c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-wrapper']/div[4]/div/div[2]/div[2]/div/div/div/div[2]/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ebc7bf9-91b5-4ec3-9b11-0fc9b92ef1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>soft-drink</value>
      <webElementGuid>a495918d-e7e7-47a6-8dcc-bf5dd8a7f35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Soft drink</value>
      <webElementGuid>e6d7d43c-1d72-41b8-bc4e-58ffce15ce75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-wrapper&quot;)/div[@class=&quot;content-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-sm-6&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;new-arrival-product&quot;]/div[@class=&quot;new-arrival-content text-center mt-3&quot;]/h4[@class=&quot;mb-1&quot;]/a[1]</value>
      <webElementGuid>608d9504-ca47-4ff7-b8f0-249c04f5f7d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-wrapper']/div[4]/div/div[2]/div[2]/div/div/div/div[2]/h4/a</value>
      <webElementGuid>b0275d39-1f41-4193-bb93-78834c0c100f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Soft drink')]</value>
      <webElementGuid>3787f1a9-a67e-4675-adf6-015c74317509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fried Chicken'])[1]/following::a[1]</value>
      <webElementGuid>30e094e1-91b2-46a5-b6d0-c4c0a342b7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[3]/following::a[2]</value>
      <webElementGuid>cf53c88e-f00c-4389-a1af-023b109fe503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fish burger'])[7]/preceding::a[1]</value>
      <webElementGuid>e607dcd0-e2c0-4c05-b94e-ae78524ba7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pepperoni pizza'])[1]/preceding::a[2]</value>
      <webElementGuid>05559bd7-48b7-4c40-988d-e28bc29840a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Soft drink']/parent::*</value>
      <webElementGuid>1bfa93a0-e884-4a72-b67b-bb787cf3519c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'soft-drink')]</value>
      <webElementGuid>faa38269-810c-48c4-a6ca-cb72e3b04177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/h4/a</value>
      <webElementGuid>4ea29d8d-a192-4b91-aaff-8b68c58a3b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'soft-drink' and (text() = 'Soft drink' or . = 'Soft drink')]</value>
      <webElementGuid>7e649cfc-ed8a-4564-95bc-a09508259b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
